### ISSUE TITLE
Masked Head Position

### ISSUE THREAD

**Issue by KyberCrow** [VirusTLNR/LethalIntelligence#11]
I'm encountering an issue wherein masked enemies will often be looking upwards; of course, this not only looks weird but completely gives them away.

I'm unaware if it's your mod that causing it or some conflict with Mirage or TooManyEmotes, but I've turned off everything you recommended in configs.

The stop/stuck motion of masked enemies (which I know you're still working on) is only occasional, whereas this issue seems to be very frequent. Please let me know if this is something you're aware of and/or what might be causing it. Cheers!

**Comment by VirusTLNR** [comment]
im aware of it, but im pretty sure its vanilla code causing it, cant prove it though.

the "stop/stuck" issue you mentioned i beleive is fixed now.. when I get a moment to look into this, I will, as im very aware it gives masked away as being masked.

Its not a conflict of mirage or too many emotes, as I see it happen in testing, im also not aware of any code in the mod that causes it to occur, but I will have to double check that.

I just spawned a masked with no mods installed (aside from the one spawning it) and the masked started looking up instantly... so defo vanilla code imho.

I will leave this issue open, until it is fixed.

**Comment by KyberCrow** [comment]
Ah, ok. Thanks for getting back to me. I've never played vanilla LC because there was no reason not to mod, lol, so I wouldn't know if that was just a quirk of vanilla code.

But yeah, if there was a way to fix it, that would obviously be fantastic. When it happens it kind of undermines/defeats the purpose of your mod, which is amazing by the way—just wanted to say that. Looking forward to how it evolves.

**Comment by VirusTLNR** [comment]
hi, thanks for the praise but im only continuing and improving on the work done by Piggy who created the mod this is built off of, id say they did 80% of the work at the least. :)

this issue is now mostly fixed in the latest version, ill continue improviing it im sure, but for me this means this issue is completed so i will close it.

linking the commit as a ref for me for the future.
https://github.com/VirusTLNR/LethalIntelligence/commit/32cc44eb4e414fd287d7c236ff6dd8ceffdd93c9

**Comment by Tenome** [comment]
I'm still encountering this, makes the mod kinda pointless since the mimics are always staring at the ceiling. I also haven't encountered any of the expanded intelligence features like them picking up walkies, etc. For now I'm going to disable it.

**Comment by VirusTLNR** [comment]
> I'm still encountering this, makes the mod kinda pointless since the mimics are always staring at the ceiling. I also haven't encountered any of the expanded intelligence features like them picking up walkies, etc. For now I'm going to disable it.

well, i beleived it was fixed, but yesterday someone actually gave me information which proved its not. I dont know how to fix the "looking up" issue yet, but im looking into it today, seems there is vanilla code when a masked "targets" a player that makes them look upwards, which is why i thought it was resolved (as in my testing, i rarely get "targeted".

as for your other issue suggesting nothing works, please provide a full log as a new issue, best to keep issues seperate so i can keep track of them.

as for not installing or disabling the mod for a while.. thats fine, everyone does as they wish, but if you wish it to be fixed, i need logs and information in order to change that.

**Comment by VirusTLNR** [comment]
hi guys, found a potential solution to the issue, and have attempted to code a fix.. please have a look at this and tell me if the head angles look correct to you in all the positions i move myself to compared to the masked

the only "weird" moments i had when recording this are in the video.. and is when the player is directly above/below the player leading to sudden snap movements, but as its unlikely this situation will ever occur, those sudden snap movements shouldent ever be seen.

in the video at the link below, the masked is unable to move, and told to always focus on me, so i can show the varying directions and positions and angles.
https://cdn.discordapp.com/attachments/1240985198485573743/1328362491389935626/Lethal_Company_2025-01-13_13-51-20.mp4?ex=67866d79&is=67851bf9&hm=bb4417c10ef61c23eccaa757504f91f3c2a679677811e6ef79dbfc0e9548d2d0&

the video can also be found here if your in the modding discord and dont wish to download it.
https://discord.com/channels/1168655651455639582/1240985198485573743/1328362496561774612

if you (or people in the discord thread) consider this a fix ill include it in the next version (0.4.0)

**Comment by VirusTLNR** [comment]
ive had some feedback now, so ive updated the mod to v0.4.0, so hopefully the issue is fixed, let me know, will leave this open a week, if i hear nothing after that, i will assume it is fixed now.
